### ISSUE TITLE
Insufficient error management

### ISSUE THREAD

**Issue by avacore1337** [avacore1337/queueSystem#10]
A "crash" occurs when the user is not logged in.

TypeError: Cannot read property 'name' of undefined
    at Socket.<anonymous> (/home/avacore/gitRepos/queueSystem/index.js:167:81)
    at Socket.emit (events.js:110:17)
    at Socket.onevent (/home/avacore/gitRepos/queueSystem/node_modules/socket.io/lib/socket.js:330:8)
    at Socket.onpacket (/home/avacore/gitRepos/queueSystem/node_modules/socket.io/lib/socket.js:290:12)
    at Client.ondecoded (/home/avacore/gitRepos/queueSystem/node_modules/socket.io/lib/client.js:193:14)
    at Decoder.Emitter.emit (/home/avacore/gitRepos/queueSystem/node_modules/socket.io/node_modules/socket.io-parser/node_modules/component-emitter/index.js:134:20)
    at Decoder.add (/home/avacore/gitRepos/queueSystem/node_modules/socket.io/node_modules/socket.io-parser/index.js:247:12)
    at Client.ondata (/home/avacore/gitRepos/queueSystem/node_modules/socket.io/lib/client.js:175:18)
    at Socket.emit (events.js:107:17)
    at Socket.onPacket (/home/avacore/gitRepos/queueSystem/node_modules/socket.io/node_modules/engine.io/lib/socket.js:99:14)
    at XHR.emit (events.js:107:17)
    at XHR.Transport.onPacket (/home/avacore/gitRepos/queueSystem/node_modules/socket.io/node_modules/engine.io/lib/transport.js:91:8)
    at callback (/home/avacore/gitRepos/queueSystem/node_modules/socket.io/node_modules/engine.io/lib/transports/polling.js:202:10)
    at Object.exports.decodePayload (/home/avacore/gitRepos/queueSystem/node_modules/socket.io/node_modules/engine.io/node_modules/engine.io-parser/lib/index.js:325:19)
    at XHR.Polling.onData (/home/avacore/gitRepos/queueSystem/node_modules/socket.io/node_modules/engine.io/lib/transports/polling.js:205:10)
    at IncomingMessage.onEnd (/home/avacore/gitRepos/queueSystem/node_modules/socket.io/node_modules/engine.io/lib/transports/polling.js:158:10)

**Comment by antbac** [comment]
This should be fixed now.
