### ISSUE TITLE
error that has been triggered a few time

### ISSUE THREAD

**Issue by avacore1337** [avacore1337/queueSystem#26]
TypeError: Cannot read property 'name' of undefined
    at Socket.<anonymous> (/home/robertwb/queueSystem/app/routes/socket.js:87:46)
    at Socket.EventEmitter.emit (events.js:98:17)
    at Socket.onevent (/home/robertwb/queueSystem/node_modules/socket.io/lib/socket.js:330:8)
    at Socket.onpacket (/home/robertwb/queueSystem/node_modules/socket.io/lib/socket.js:290:12)
    at Client.ondecoded (/home/robertwb/queueSystem/node_modules/socket.io/lib/client.js:193:14)
    at Decoder.Emitter.emit (/home/robertwb/queueSystem/node_modules/socket.io/node_modules/socket.io-parser/node_modules/component-emitter/index.js:134:20)
    at Decoder.add (/home/robertwb/queueSystem/node_modules/socket.io/node_modules/socket.io-parser/index.js:247:12)
    at Client.ondata (/home/robertwb/queueSystem/node_modules/socket.io/lib/client.js:175:18)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.onPacket (/home/robertwb/queueSystem/node_modules/socket.io/node_modules/engine.io/lib/socket.js:99:14)
    at WebSocket.EventEmitter.emit (events.js:117:20)
    at WebSocket.Transport.onPacket (/home/robertwb/queueSystem/node_modules/socket.io/node_modules/engine.io/lib/transport.js:91:8)
    at WebSocket.Transport.onData (/home/robertwb/queueSystem/node_modules/socket.io/node_modules/engine.io/lib/transport.js:102:8)
    at WebSocket.onData (/home/robertwb/queueSystem/node_modules/socket.io/node_modules/engine.io/lib/transports/websocket.js:75:30)
    at WebSocket.EventEmitter.emit (events.js:98:17)
    at Receiver.ontext (/home/robertwb/queueSystem/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib/WebSocket.js:797:10)

**Comment by avacore1337** [comment]
has not appeared for a very long time. Probably fixed alongside many other things.
