### ISSUE TITLE
ldapjs-hotfix not specified in dependencies

### ISSUE THREAD

**Issue by Rondom** [avacore1337/queueSystem#30]
Trying to run the application I get:

```
Error: Cannot find module 'ldapjs-hotfix'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/andreas/cvs/queueSystem/app/index.js:15:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

An npm install fixes that. The dependency should be added to package.json, maybe

**Comment by avacore1337** [comment]
It should be fixed now. That's what I get for coding when tired and running -s instead of --save.
